CREATE TABLE dbo.SKU
(
ID INT NOT NULL IDENTITY,
Code AS s + ID,
Name VARCHAR(30) NOT NULL,
CONSTRAINT PK_SKU PRIMARY KEY(ID),
CONSTRAINT UNQ_SKU_Code UNIQUE(Code)
);

CREATE TABLE dbo.Family
(
ID INT NOT NULL IDENTITY,
SurName VARCHAR(30) NOT NULL,
BudgetValue MONEY NOT NULL,
CONSTRAINT PK_Family PRIMARY KEY(ID)
);

CREATE TABLE dbo.Basket
(
ID INT NOT NULL IDENTITY,
ID_SKU INT NOT NULL,
ID_Family INT NOT NULL,
Quantity INT NOT NULL CHECK(Quantity >= 0),
Value INT NOT NULL,
PurchaseDate DATETIME NOT NULL DEFAULT(SYSDATETIME()),
DiscountValue NUMERIC(4, 2) NOT NULL,
CONSTRAINT PK_Basket PRIMARY KEY(ID),
CONSTRAINT FK_Basket_SKU FOREIGN KEY(ID_SKU)
    REFERENCES dbo.SKU(ID),
CONSTRAINT FK_Basket_Family FOREIGN KEY(ID_Family)
    REFERENCES dbo.Family(ID)
);